name: CI

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node_version: [12, 14, 16]
            fail-fast: false

        name: 'Building in: node-${{ matrix.node_version }}, ${{ matrix.os }}'
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Yarn install
              uses: borales/actions-yarn@v2.3.0
              if: steps.node_modules_cache.outputs.cache-hit != 'true'
              with:
                  cmd: install # yarn install

            - name: Build bundle
              run: npm run build

    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Yarn install
              uses: borales/actions-yarn@v2.3.0
              if: steps.node_modules_cache.outputs.cache-hit != 'true'
              with:
                  cmd: install # yarn install

            - name: eslint
              run: eslint ./src

    typings:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Yarn install
              uses: borales/actions-yarn@v2.3.0
              if: steps.node_modules_cache.outputs.cache-hit != 'true'
              with:
                  cmd: install # yarn install

            - name: typescript types checker
              run: tsc
