name: Docs Deploy

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    docs-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v2
              with:
                  ref: master

            - name: Use Node.js Env ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: '12'

            - name: Use node_modules cache
              uses: actions/cache@v2
              id: node_modules_cache
              with:
                  path: '**/node_modules/**/*'
                  key: ${{ runner.os }}-node_modules_cache-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-node_modules_cache-${{ hashFiles('**/yarn.lock') }}

            - name: Yarn install
              uses: borales/actions-yarn@v2.3.0
              if: steps.node_modules_cache.outputs.cache-hit != 'true'
              with:
                  cmd: install

            - name: Docs Build
              run: npm run docs:build

            - name: Docs Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  commit-message: 'docs: 🚀Github Pages Deployment.🔖'
                  branch: gh-pages
                  folder: docs-dist
                  token: ${{ secrets.GH_TOKEN }}
